# Form implementation generated from reading ui file '.\ui\components\predict_gait_stack_one_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_predictgait_stack_page_one(object):
    def setupUi(self, predictgait_stack_page_one):
        predictgait_stack_page_one.setObjectName("predictgait_stack_page_one")
        predictgait_stack_page_one.resize(738, 451)
        self.verticalLayout = QtWidgets.QVBoxLayout(predictgait_stack_page_one)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.strike_image_holder_wid = QtWidgets.QWidget(parent=predictgait_stack_page_one)
        self.strike_image_holder_wid.setObjectName("strike_image_holder_wid")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.strike_image_holder_wid)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.strike_image_1 = QtWidgets.QLabel(parent=self.strike_image_holder_wid)
        self.strike_image_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.strike_image_1.setText("")
        self.strike_image_1.setPixmap(QtGui.QPixmap(":/strikes/images/strikes/strike_img_1.png"))
        self.strike_image_1.setScaledContents(True)
        self.strike_image_1.setObjectName("strike_image_1")
        self.horizontalLayout.addWidget(self.strike_image_1)
        self.strike_image_2 = QtWidgets.QLabel(parent=self.strike_image_holder_wid)
        self.strike_image_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.strike_image_2.setText("")
        self.strike_image_2.setScaledContents(True)
        self.strike_image_2.setObjectName("strike_image_2")
        self.horizontalLayout.addWidget(self.strike_image_2)
        self.strike_image_3 = QtWidgets.QLabel(parent=self.strike_image_holder_wid)
        self.strike_image_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.strike_image_3.setText("")
        self.strike_image_3.setObjectName("strike_image_3")
        self.horizontalLayout.addWidget(self.strike_image_3)
        self.strike_image_4 = QtWidgets.QLabel(parent=self.strike_image_holder_wid)
        self.strike_image_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.strike_image_4.setText("")
        self.strike_image_4.setObjectName("strike_image_4")
        self.horizontalLayout.addWidget(self.strike_image_4)
        self.strike_image_5 = QtWidgets.QLabel(parent=self.strike_image_holder_wid)
        self.strike_image_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.strike_image_5.setText("")
        self.strike_image_5.setObjectName("strike_image_5")
        self.horizontalLayout.addWidget(self.strike_image_5)
        self.strike_image_6 = QtWidgets.QLabel(parent=self.strike_image_holder_wid)
        self.strike_image_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.strike_image_6.setText("")
        self.strike_image_6.setObjectName("strike_image_6")
        self.horizontalLayout.addWidget(self.strike_image_6)
        self.strike_image_7 = QtWidgets.QLabel(parent=self.strike_image_holder_wid)
        self.strike_image_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.strike_image_7.setText("")
        self.strike_image_7.setObjectName("strike_image_7")
        self.horizontalLayout.addWidget(self.strike_image_7)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 10)
        self.horizontalLayout.setStretch(2, 10)
        self.horizontalLayout.setStretch(3, 10)
        self.horizontalLayout.setStretch(4, 10)
        self.horizontalLayout.setStretch(5, 10)
        self.horizontalLayout.setStretch(6, 10)
        self.verticalLayout.addWidget(self.strike_image_holder_wid)
        self.pbar_container_wid = QtWidgets.QWidget(parent=predictgait_stack_page_one)
        self.pbar_container_wid.setObjectName("pbar_container_wid")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pbar_container_wid)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.pbar_container_wid)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 4)

        self.retranslateUi(predictgait_stack_page_one)
        QtCore.QMetaObject.connectSlotsByName(predictgait_stack_page_one)

    def retranslateUi(self, predictgait_stack_page_one):
        _translate = QtCore.QCoreApplication.translate
        predictgait_stack_page_one.setWindowTitle(_translate("predictgait_stack_page_one", "Form"))
