# Form implementation generated from reading ui file '.\ui\components\predict_grpah_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_predict_gait_content(object):
    def setupUi(self, predict_gait_content):
        predict_gait_content.setObjectName("predict_gait_content")
        predict_gait_content.resize(653, 392)
        self.verticalLayout = QtWidgets.QVBoxLayout(predict_gait_content)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.predict_graph1_btn = QtWidgets.QPushButton(parent=predict_gait_content)
        self.predict_graph1_btn.setObjectName("predict_graph1_btn")
        self.horizontalLayout.addWidget(self.predict_graph1_btn)
        self.predict_graph1_btn_2 = QtWidgets.QPushButton(parent=predict_gait_content)
        self.predict_graph1_btn_2.setObjectName("predict_graph1_btn_2")
        self.horizontalLayout.addWidget(self.predict_graph1_btn_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=predict_gait_content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.strike_image_container = QtWidgets.QWidget(parent=self.page)
        self.strike_image_container.setObjectName("strike_image_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.strike_image_container)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2.addWidget(self.strike_image_container)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graph_container = QtWidgets.QWidget(parent=self.page_2)
        self.graph_container.setObjectName("graph_container")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.graph_container)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3.addWidget(self.graph_container)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.widget = QtWidgets.QWidget(parent=predict_gait_content)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cpbar_1 = QtWidgets.QLabel(parent=self.widget)
        self.cpbar_1.setStyleSheet("background-color:red;\n"
"border-radius:50px;\n"
"")
        self.cpbar_1.setText("")
        self.cpbar_1.setObjectName("cpbar_1")
        self.horizontalLayout_2.addWidget(self.cpbar_1)
        self.hline_1 = QtWidgets.QFrame(parent=self.widget)
        self.hline_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.hline_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hline_1.setObjectName("hline_1")
        self.horizontalLayout_2.addWidget(self.hline_1)
        self.rpbar_1 = QtWidgets.QLabel(parent=self.widget)
        self.rpbar_1.setText("")
        self.rpbar_1.setObjectName("rpbar_1")
        self.horizontalLayout_2.addWidget(self.rpbar_1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(583, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 20)
        self.verticalLayout.setStretch(2, 8)

        self.retranslateUi(predict_gait_content)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(predict_gait_content)

    def retranslateUi(self, predict_gait_content):
        _translate = QtCore.QCoreApplication.translate
        predict_gait_content.setWindowTitle(_translate("predict_gait_content", "Form"))
        self.predict_graph1_btn.setText(_translate("predict_gait_content", "Graph 1"))
        self.predict_graph1_btn_2.setText(_translate("predict_gait_content", "Graph "))
