# Form implementation generated from reading ui file '.\ui\components\predict_image_stream_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_strike_image_container(object):
    def setupUi(self, strike_image_container):
        strike_image_container.setObjectName("strike_image_container")
        strike_image_container.resize(564, 517)
        self.verticalLayout = QtWidgets.QVBoxLayout(strike_image_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=strike_image_container)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.strike_image_1 = QtWidgets.QLabel(parent=self.widget)
        self.strike_image_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.strike_image_1.setText("")
        self.strike_image_1.setPixmap(QtGui.QPixmap(":/strikes/images/strikes/strike_img_1.png"))
        self.strike_image_1.setScaledContents(True)
        self.strike_image_1.setObjectName("strike_image_1")
        self.horizontalLayout.addWidget(self.strike_image_1)
        self.strike_image_2 = QtWidgets.QLabel(parent=self.widget)
        self.strike_image_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.strike_image_2.setText("")
        self.strike_image_2.setPixmap(QtGui.QPixmap(":/images/strikes/strike_img_2.png"))
        self.strike_image_2.setScaledContents(True)
        self.strike_image_2.setObjectName("strike_image_2")
        self.horizontalLayout.addWidget(self.strike_image_2)
        self.strike_image_3 = QtWidgets.QLabel(parent=self.widget)
        self.strike_image_3.setText("")
        self.strike_image_3.setObjectName("strike_image_3")
        self.horizontalLayout.addWidget(self.strike_image_3)
        self.strike_image_4 = QtWidgets.QLabel(parent=self.widget)
        self.strike_image_4.setText("")
        self.strike_image_4.setObjectName("strike_image_4")
        self.horizontalLayout.addWidget(self.strike_image_4)
        self.strike_image_5 = QtWidgets.QLabel(parent=self.widget)
        self.strike_image_5.setText("")
        self.strike_image_5.setObjectName("strike_image_5")
        self.horizontalLayout.addWidget(self.strike_image_5)
        self.strike_image_6 = QtWidgets.QLabel(parent=self.widget)
        self.strike_image_6.setText("")
        self.strike_image_6.setObjectName("strike_image_6")
        self.horizontalLayout.addWidget(self.strike_image_6)
        self.strike_image_7 = QtWidgets.QLabel(parent=self.widget)
        self.strike_image_7.setText("")
        self.strike_image_7.setObjectName("strike_image_7")
        self.horizontalLayout.addWidget(self.strike_image_7)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(strike_image_container)
        QtCore.QMetaObject.connectSlotsByName(strike_image_container)

    def retranslateUi(self, strike_image_container):
        _translate = QtCore.QCoreApplication.translate
        strike_image_container.setWindowTitle(_translate("strike_image_container", "Form"))
