# Form implementation generated from reading ui file '.\ui\components\predictgait_ctl_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_predict_ctl_wid(object):
    def setupUi(self, predict_ctl_wid):
        predict_ctl_wid.setObjectName("predict_ctl_wid")
        predict_ctl_wid.resize(802, 339)
        self.verticalLayout = QtWidgets.QVBoxLayout(predict_ctl_wid)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.predict_graph1_btn = QtWidgets.QPushButton(parent=predict_ctl_wid)
        self.predict_graph1_btn.setObjectName("predict_graph1_btn")
        self.horizontalLayout.addWidget(self.predict_graph1_btn)
        self.predict_graph1_btn_2 = QtWidgets.QPushButton(parent=predict_ctl_wid)
        self.predict_graph1_btn_2.setObjectName("predict_graph1_btn_2")
        self.horizontalLayout.addWidget(self.predict_graph1_btn_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=predict_ctl_wid)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_one = QtWidgets.QWidget()
        self.page_one.setObjectName("page_one")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_one)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget.addWidget(self.page_one)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(predict_ctl_wid)
        QtCore.QMetaObject.connectSlotsByName(predict_ctl_wid)

    def retranslateUi(self, predict_ctl_wid):
        _translate = QtCore.QCoreApplication.translate
        predict_ctl_wid.setWindowTitle(_translate("predict_ctl_wid", "Form"))
        self.predict_graph1_btn.setText(_translate("predict_ctl_wid", "Graph 1"))
        self.predict_graph1_btn_2.setText(_translate("predict_ctl_wid", "Graph "))
